theme: jekyll-theme-minimal
title: maks232
description: ğŸ‘¨â€ğŸ’¼ ğŸš´ ğŸƒâ€â™‚ï¸ ğŸ‘¨â€ğŸ³ ğŸº ğŸ›¶ ğŸ“ â›°ï¸ ğŸš¶â€â™‚ï¸ ğŸ’»
logo: https://secure.gravatar.com/avatar/092f956a3dac40441f35863e7c333d5a?s=200
