theme: jekyll-theme-minimal
title: maks232
description: ğŸ‘¨â€ğŸ’¼ ğŸš´ ğŸƒâ€â™‚ï¸ ğŸ‘¨â€ğŸ³ ğŸº ğŸ›¶ ğŸ“ â›°ï¸ ğŸš¶â€â™‚ï¸ ğŸ’»
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: artemsheludko # add your Github handle
social-linkedin: # add your Linkedin handle
social-email: maksim.bock@gmail.com

logo: https://secure.gravatar.com/avatar/092f956a3dac40441f35863e7c333d5a?s=200
